temporaryily bug fix (as rtorrent.net is down)

diff --git a/scripts/rtinst b/scripts/rtinst
--- a/scripts/rtinst
+++ b/scripts/rtinst
@@ -20,7 +20,6 @@ PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/bin:/sbin
 
 #url's of the major components
 rt_url="http://rtorrent.net/downloads/"
-rt_url="https://github.com" # temporaryily fix
 
 xmlrpc_url="https://svn.code.sf.net/p/xmlrpc-c/code/stable/"
 xmlrpc_url_alt="https://github.com/mirror/xmlrpc-c"
@@ -334,8 +333,7 @@ done
 
 echo
 echo "Checking major 3rd party components"
-echo -n "Rtorrent: "; check_url $rt_url && echo "OK" || { echo "FAIL"; major_repo=1; }
-
+# echo -n "Rtorrent: "; check_url $rt_url && echo "OK" || { echo "FAIL"; major_repo=1; }
 echo -n "xmlrpc-c: "; check_url $xmlrpc_url && echo "OK" ||  xmlrpc_repo=1
 
 if [[ $xmlrpc_repo = 1 ]]; then
diff --git a/scripts/rtupdate b/scripts/rtupdate
--- a/scripts/rtupdate
+++ b/scripts/rtupdate
@@ -16,7 +16,6 @@ PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/bin:/sbin
 osname=$(lsb_release -si)
 relno=$(lsb_release -sr | cut -d. -f1)
 sourcedir='http://rtorrent.net/downloads/'
-sourcedir='https://github.com' # temporaryily fix
 
 xmlrpc_url='https://svn.code.sf.net/p/xmlrpc-c/code/stable/'
 xmlrpcloc='svn://svn.code.sf.net/p/xmlrpc-c/code/stable/'
@@ -125,7 +124,7 @@ if [[ $xmlrpc_repo = 1 ]]; then
   check_url $xmlrpc_url && { echo "OK";  xmlrpc_repo=0; } || { echo "FAIL"; xmlrpc_repo=1; }
 fi
 
-echo -n "rtorrent: "; check_url $sourcedir && echo "OK" || { echo "FAIL"; rt_repo=1; }
+# echo -n "rtorrent: "; check_url $sourcedir && echo "OK" || { echo "FAIL"; rt_repo=1; }
 
 if [ $rt_repo = 1 ]; then
   echo "The libtorrent/rtorrent file repositoy is offline"
@@ -168,16 +167,16 @@ if [ -z $passed_rtvers ]; then
 
 else
 
-    if [ "$passed_rtvers" = "latest" ] || [ $(wget -q -O - $sourcedir | grep -o "rtorrent-$passed_rtvers.tar.gz" | wc -l) -eq 0 ]; then
-        if [ "$passed_rtvers" != "latest" ]; then
-            echo "Could not find $passed_rtvers so using latest version instead"
-        fi
-        libvers=$latest_libvers
-        rtvers=$latest_rtvers
-    else
+#    if [ "$passed_rtvers" = "latest" ] || [ $(wget -q -O - $sourcedir | grep -o "rtorrent-$passed_rtvers.tar.gz" | wc -l) -eq 0 ]; then
+#        if [ "$passed_rtvers" != "latest" ]; then
+#            echo "Could not find $passed_rtvers so using latest version instead"
+#        fi
+#        libvers=$latest_libvers
+#        rtvers=$latest_rtvers
+#    else
         libvers=$(echo $passed_rtvers | awk -F. -v OFS=. '{$2='$(( $(echo $rtversion | cut -d. -f2) + 4 ))'; print }')
         rtvers=$passed_rtvers
-    fi
+#    fi
 
 fi
 
